language: node_js
node_js:
  "node"
cache: yarn
script:
  - npm run clean
  - npm run build
  - cp CNAME _book
  - touch _book/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  name: Publishment Bot
  on:
    branch: gh-pages
  local_dir: _book
